=== Rodriwp/pfat/xml/practica_1/pelicula.dtd
<!ELEMENT CatalogoPeliculas (Pelicula*)>
<!ELEMENT Pelicula (titulo,director,actor+,genero+,nacionalidad+,clasificacion?)>
<!ELEMENT titulo (#PCDATA)>
<!ELEMENT director (#PCDATA)>
<!ELEMENT actor (nombre,personaje*)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT personaje (#PCDATA)>
<!ELEMENT genero (#PCDATA)> 
<!ELEMENT nacionalidad (#PCDATA)>
<!ELEMENT clasificacion (#PCDATA)>

<!ATTLIST Pelicula  aÃ±o CDATA #REQUIRED >
<!ATTLIST Pelicula  duracion CDATA #REQUIRED>

<!ENTITY tp "Todos los Publicos">

=== Rodriwp/pfat/xml/practica_1/starwars.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE CatalogoPeliculas SYSTEM "./pelicula.dtd">
<CatalogoPeliculas>
    <Pelicula  año="1999" duracion="121 minutos">
        <titulo>Star Wars:La amenaza fantasma </titulo>
        <director>George Lucas</director>
        <actor>
            <nombre>Harrison Ford</nombre>
            <personaje>Han Solo</personaje>
            <personaje>Han Solo Congelado</personaje>
        </actor>       
        <genero>ciencia ficcion</genero>
        <genero>clasico</genero>
        <nacionalidad> USA</nacionalidad>
        <clasificacion>&tp;</clasificacion>
    </Pelicula>
    <Pelicula  año="2002" duracion="121 minutos">
        <titulo>Star Wars:El ataque de los clones</titulo>
        <director>George Lucas</director>
        <actor>
            <nombre>Harrison Ford</nombre>
            <personaje>Han Solo</personaje>
            <personaje>Han Solo Congelado</personaje>
        </actor>       
        <genero>ciencia ficcion</genero>
        <genero>clasico</genero>
        <nacionalidad> USA</nacionalidad>
    </Pelicula>
</CatalogoPeliculas>
